version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/dotnet-project
    steps:
      - checkout
      - attach_workspace:
          at: ~/dotnet-project
      - run:
          name: build 
          command: dotnet publish ${PROJECT_PATH} -c Release
      - persist_to_workspace:
          root: '.'
          paths: Hello/bin/Release/netcoreapp3.1/publish/*
  
  deploy:
    machine:
        enabled: true
    working_directory: ~/dotnet-project
    steps:
        - attach_workspace:
            at: ~/dotnet-project
        - add_ssh_keys
        - run: ls Hello
        - run: scp -oStrictHostKeyChecking=no -r ${BIN_DIR} ${USER_NAME}@${HOST_NAME}:${DST_APP_DIR}

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build