version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: build 
          command: dotnet publish ${SRC_APP_DIR}/${SOLUSION_NAME} -c Release
      - persist_to_workspace:
          root: '${SRC_APP_DIR}/bin/Release'
          paths:
              - publish/*
  deploy:
    machine:
        enabled: true
    steps:
        - attach_workspace:
            at: '${SRC_APP_DIR}/bin/Release'
        - add_ssh_keys
        - run: scp -oStrictHostKeyChecking=no -r ${SRC_APP_DIR} ${USER_NAME}@${HOST_NAME}:${DST_APP_DIR}
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build 
          filters:
              branches:
                  only:
                      - master