version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build $SolutionName
workflows:
  version: 2.1
  buildAll:
    jobs:
      - build