version: '3'

services:
  dotnet_db:
    container_name: dotnet_db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    hostname: dotnet_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "db-data:/var/lib/mysql"
      - "./db/my.conf:/etc/mysql/my.conf"
      - "./db/init/:/docker-entrypoint-initdb.d"
    networks:
      - esnet

  dotnet_elk:
    build:
      context: .
      dockerfile: ./elk/Dockerfile
    container_name: dotnet_elk
    ports: 
      - 5601:5601 
      - 9200:9200 
      - 5044:5044
    networks:
      - esnet
  
  dotnet_filebeat:
    mem_limit: 64m
    build: 
      context: .
      dockerfile: ./filebeat/Dockerfile
    container_name: dotnet_filebeat
    volumes:
      - ../Hello/logs:/logs
    links:
      - dotnet_elk:dotnet_elk
    networks:
      - esnet

  dotnet_web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: dotnet_web
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "server=dotnet_db;port=3306;uid=root;pwd=password;database=asp_net_sample"
      ELASTIC_SEARCH_SERVER: "http://dotnet_elk:9200"
    volumes:
      - ../:/dotnet-app
    command: /bin/bash -c "while sleep 1000; do :; done"
    stdin_open: true
    links:
      - dotnet_elk:dotnet_elk
      - dotnet_db:dotnet_db 
    networks:
      - esnet

volumes:
  db-data:
    driver: local

networks:
  esnet:
