version: '3'

services:
  dotnet_db:
    image: mysql:8.0
    container_name: dotnet_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: password
    volumes:
      - "db_data:/var/lib/mysql"
      - "./db/my.conf:/etc/mysql/my.conf"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

  dotnet_elk:
    image: sebp/elk:oss-792
    container_name: dotnet_elk
    ports: 
      - 5601:5601 
      - 9200:9200
    volumes:
      - "./elk/logstash.conf:/etc/logstash/conf.d/logstash.conf"

  dotnet_filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.2
    container_name: dotnet_filebeat
    user: root
    mem_limit: 64m
    volumes:
      - "../Hello/logs:/logs"
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"

  dotnet_web:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    container_name: dotnet_web
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "server=dotnet_db;port=3306;uid=root;pwd=password;database=asp_net_sample"
      ELASTIC_SEARCH_SERVER: "http://dotnet_elk:9200"
    volumes:
      - ../:/dotnet-app
    command: /bin/bash -c "while sleep 1000; do :; done"

volumes:
  db_data:
    driver: local
